# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 703e76b931b1c6184e395d8e0fe639c8fa64ec718c8e6aee555fd92baf3ba4240d08e2838c1718e2d8807ddbb92f4d7cb3ae4571fde0ecd74114b60705a65db4

test:
  secret_key_base: 32f1013463a97c76210731f28f110de4e54d002a3ecd15885ea300b8f084bb31218f0dc9b8ce3c137de7bec493c536a6655e0ad31be6581c5a942d1274a09033

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
